### ISSUE TITLE
Long Note Names in Quick Switch Issue

### ISSUE THREAD

**Issue by mleo2003** [radekkozak/discordian#13]
Some of my note names/paths to my notes are longer than the Quick Switch Modal that shows the potential matches to what you are looking for. The Default theme shows them properly, but Discordian has the titles word wrap to the next line, but the other items are "on top" or overlap on the words from the other elements, making it hard/impossible to see what those last words say.

**Comment by radekkozak** [comment]
Hi, i will definitely look into this, i might've missed sth. Any screenshot is always appreciated and helpful in such visual issues

Thanks in advance

**Comment by mleo2003** [comment]
Thanks again for the quick reply. Here's an example of it breaking in screenshot.
![Screenshot at 2021-01-09 12-30-16](https://user-images.githubusercontent.com/3462000/104108068-80798c00-5276-11eb-867b-f1ab792165ef.png)

**Comment by radekkozak** [comment]
Thanks for the screen: I already fixed the issue - will appear in next release coming up tomorrow. But if you're able to work it out via Obsidian CSS snippets i can provide the easy fix for ya right now. Let me know if you want to wait or get it working without the wait

**Comment by mleo2003** [comment]
Thanks for finding the fix so fast. It doesn't come up that often, so I can be patient and wait for it for now (and so I don't have to undo the fix later to make sure nothing else is messing with me in the future).

**Comment by radekkozak** [comment]
Great, i will let you know when it's out
