### ISSUE TITLE
Horizontal line of emojis turns vertical

### ISSUE THREAD

**Issue by Krishnu-hm** [radekkozak/discordian#25]
This happens
![image](https://user-images.githubusercontent.com/70955978/107876317-4477bd80-6eeb-11eb-9ed3-262a3413c11a.png)

**Comment by radekkozak** [comment]
Hi @Krishnu-hm  thanks for letting me know - i don't use emojis myself so i was not aware of such weird behaviour - i will try to look into it

It would be helpful if you could atatch the relevant note (or part of it causing this) I will test it against my current setup and see what i can do in the upcoming release

Cheers

**Comment by radekkozak** [comment]
Just letting you know i have fixed the issue - new version of Discordian will be released soon with the patch

All best from Poland
