### ISSUE TITLE
Wiki Links in Tables Break Formatting

### ISSUE THREAD

**Issue by nfarrar** [radekkozak/discordian#37]
It looks like when you put wiki links (potentially any markup) in a table, it breaks the formatting.

![image](https://user-images.githubusercontent.com/831349/109576729-94d94880-7ab1-11eb-806c-3a9dcee9f662.png)

Note: I'm using the [Advanced Tables](]https://github.com/tgrosinger/advanced-tables-obsidian) plugin.

**Comment by radekkozak** [comment]
Hi Nathan, you're right, there was something off indeed. I have already fixed the issue

![fixed-tables](https://user-images.githubusercontent.com/2744747/109645122-b17b8c00-7b56-11eb-952f-f9f2b1ce0dbb.png)

New Discordian version will be up today with bunch of fixes including this one. I would provide you with the snippet but this was not one-liner so sorry... hope you can wait couple of hours 

Thanks for reporting this /cc @nfarrar
