### ISSUE TITLE
Multi Paragraph Block Quote Rendering

### ISSUE THREAD

**Issue by craigwelch** [radekkozak/discordian#38]
> blockquote, single line, totally cool

> blockquote
> 
> multiple line not working in Discordia theme

![Screen Shot 2021-03-09 at 5 11 53 AM](https://user-images.githubusercontent.com/12218024/110417472-fabb6680-8095-11eb-9641-731be6e511a9.jpg)

**Comment by radekkozak** [comment]
Hi Craig, thanks for letting me know. Indeed something was off

I already see what the problem is so i'm fixing this as we speak

Thanks again /cc @craigwelch

**Comment by radekkozak** [comment]
Hi again @craigwelch - just released the hotfix for your issue - please update theme - all should be a-ok now.

**Comment by craigwelch** [comment]
@radekkozak - updated and can confirm that it is functioning properly now

FYI - the theme update in Obsidian isn't working (or may need more time to pickup changes) → to update i simply deleted the theme and reloaded

![Screen Shot 2021-03-10 at 9 13 20 AM](https://user-images.githubusercontent.com/12218024/110597939-7c3bf300-8181-11eb-8869-75e5f69971c7.jpg)

**Comment by radekkozak** [comment]
@craigwelch - glad it works now, and once again thanks for letting me know

As to updating theme, this is one feature i miss as well and wish it would work similar to Community plugins updates. 
From what i know from Obsidian devs recommended way for now is to: 
- Browse themes
- Pick up a theme of choice again -> "Use" button : it will simply override current one with newest version

Not elegant i think but we're stuck with it for now until Obsidian devs cook sth better
