### ISSUE TITLE
fold gutter overlaps covers the writing area in editor mode

### ISSUE THREAD

**Issue by s-kyy** [radekkozak/discordian#43]
OS: Windows
Discordian version: 0.8.5
Obsidian: Version: 0.11.13

When viewing text in editor mode there's something overlapping the the left-side of the writing area

This is some example text:
```
OS: Windows
Discordian version: 0.8.5
Obsidian: Version: 0.11.13
```

This is what it looks like in preview mode:
![image](https://user-images.githubusercontent.com/19920083/113951903-8aae1680-97e2-11eb-98d7-399d96236355.png)

Note: I was able to fix it with:
```
.CodeMirror-foldgutter {
  width: 0px !important; /*<---- edited this line!*/
  display: none;
}
```
Although I'm not sure if this affected this [issue](https://github.com/radekkozak/discordian/issues/42#issue-852950703) I posted a few minutes ago or and how the toggle icons are displayed.

**Comment by nfarrar** [comment]
Having same issue ... 

![image](https://user-images.githubusercontent.com/831349/114472524-9cf7ce00-9baf-11eb-9d20-460407793588.png)

**Comment by bagameow** [comment]
https://github.com/radekkozak/discordian/blob/2fb4af355a70d3c39153fbcfeabd1a7a4b708bd0/obsidian.css
you can use prior version first.

**Comment by djbtalk** [comment]
Facing same issue after updating. Started using previous version which was ok.

**Comment by radekkozak** [comment]
Hi guys / @djbtalk @bagameow @nfarrar @s-kyy / very sorry for quite a delay on the problem. As i mentioned in another issue - i just get out of very nasty Covid situation few days ago and i'm still shocked a little and messed up. But i'm trying slowly to get my head around things now.

I will try to look into things to help you all with the issue. I missed quite few Obsidian updates so it is probably some changes there in official editor code that moved few things around. I will try to get Discordian up to speed with newest Obsidian version

Thank you all mates for the patience. Glad the previous version works for you for the moment

**Comment by bagameow** [comment]
wish all the best

**Comment by radekkozak** [comment]
Thank you @bagameow , kind word is always helping

All best from Poland to you
