### ISSUE TITLE
cssclass: img-captions, img-grid

### ISSUE THREAD

**Issue by shauxesis** [radekkozak/discordian#44]
Hi @radekkozak 

Just wanted to report strange behavior of theme when using cssclass in YAML at top of a note -- preview formatting is all over the place and I can't figure out why. 

```
---
cssclass: img-captions, img-grid
---
```

Please see attached

![screenshot 2021 04 19 00 07 14](https://user-images.githubusercontent.com/32718268/115163870-77812d80-a0a3-11eb-8a83-06aa156983f3.png)

Images are working wonderfully, however certain markdown syntax line inline code, my table of contents (links to in note headers) and footnotes are doing weird and wonderful things.

I'm not sure how to fix this myself and would be grateful if you could take a look. 

All the best!

**Comment by radekkozak** [comment]
Hi @shauxesis very sorry for quite a delay - i just get out of very nasty Covid situation few days ago, still shocked a little and messed up but i'm trying slowly to get my head around things now.

I'm eager to help you with the issue, could you please send me your problematic note so i could better debug the issue 

Thank you, and thanks for the patience

**Comment by shauxesis** [comment]
Hi Radek,

So sorry to hear you have not been well, but very glad to know you are on the mend! Very scary this whole Covid situation! Please, no rush on this, just make sure you take care of your health first!

As and when you can take a look, here is a sample attachment (with the image used). I am experiencing the same problem in other notes with more images — I think the img-grid is reading some formatted text as an image and therefore applying the css styling — I don’t seem to have this issue with the default Obsidian theme (text looks normal) — so I can’t seem to locate the possible issue with the text itself. 

Maybe you can see something I have missed?

Thank you for your help in advance.

Shandé

**Comment by radekkozak** [comment]
Thank you for understanding Shandé. 

Yes, it was quite scary, still recovering from the whole experience. But per med outlines besides taking care of physical  i gotta exercise my mind as well so no worries. I think it would actually be good to try to solve few things

To that end: i think i'm missing the attachment, the actual `.md` note that's causing the trouble would be most helpful (also i assume you use the newest version of Obsidian ?)

Thank you /cc @shauxesis

**Comment by shauxesis** [comment]
Hey Radek,

The md is attached to the email below this one (see snapshot).

If you still are unable to locate it, I’ll send again as soon as I am back at my MacBook.

Also, yes latest version of Obsidian 👍

Take care of yourself!

Shande







Shandé

**Comment by shauxesis** [comment]
Attached above 👍

Shande

**Comment by radekkozak** [comment]
This is very weird - i think github is somehow eating the file you're trying to attach. Maybe you need to zip it first or something - not sure

If you could kindly maybe send it to me directly at [radoslaw.kozak@gmail.com](mailto:radoslaw.kozak@gmail.com)  it would be the simplest option. I think i know what might be going on but want to make sure and confirm with your .md note

Thanks again

**Comment by radekkozak** [comment]
Hi Shandé / @shauxesis 
just pasting the email i sent you and letting you know i was able to fix the problem with image grids and captions you were having. 

It was a nasty one i must admit as **Obsidian starting from version 0.11.3 changed how it internally groups images together entirely** !

Not to bore you with details but i will explain it more in description of Discordian theme on github and at the Discordian chat in forum https://forum.obsidian.md/t/discordian-theme/10880/1 when 0.8.6 version will launch (that is TODAY ;)

Long story short: prior to Obsidian changes i advised everyone to use img-grid **OR** img-captions in their note **as their css apply globally to all images in the note**. This was main problem with the note you sent me - hence the whole havoc around it

Anyway: i decided to fix that as much as it is possible with how Obsidian works (not everything is possible unfortunately) - and took it up a notch - **you will be able to use both: grids and captions inside one note** but with restrictions.

Still advise to use them separately inside one note :) it’s easier that way

Anyway, thank you very much for letting me know about all of the problems. I very much appreciate it as it makes the theme better and cleaner

In the next days i will try to look what else has changed in Obsidian in the period when i was out of the grid
